# -*- coding: utf-8 -*-
"""problem1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpeE2tfrUmFjxn-Z0M3b84O80fMLXc1b
"""

print("Twinkle, twinkle, little star, how I wonder what you are. Up above the world so high,")
print("like a diamond in the sky. Twinkle, twinkle, little star, how I wonder what you are")

print("When the blazing sun is set, and the grass with dew is wet. Then you show your little")
print("light, twinkle, twinkle all the night. Twinkle, twinkle little star, how I wonder what you are.")

print("Then the traveler in the dark thanks you for your tiny spark. How could he see where to ")
print("go if you did not twinkle so? Twinkle, twinkle little star, how I wonder what you are.")

print("As your bright and tiny spark lights the traveler in the dark, though I know not what you")
print("are, twinkle, twinkle, little star. Twinkle, twinkle, little star, how I wonder what you are.")